# Generated by Django 5.0 on 2023-12-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoservice', '0002_photo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
